name: WraithavenSculpt
main: net.whg.whsculpt.WraithavenSculpt
version: 0.1.0
api-version: 1.17
depend: [WorldEdit, HavensGames-Utils]
commands:
  whsculpt:
    description: Wraithaven Sculpt commands.
    usage: /whsculpt
